customhost = "employee.cfmnjh6ybhob.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "limcheeziong-employee"
customregion = "us-east-1"
